[package]
name = "org-impaste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
emacs = "0.18.0"
